### ISSUE TITLE
Method calls may be reversed in BasicSolver.solver.

### ISSUE THREAD

**Issue by cia-rana** [mdrft/wildcat#21]
In BasicSolver.solver, I think if the row of `self.ising_interactions` is 0, then we should call `self.build_ising_interactions()` to build `self.ising_interactions` with `self.qubo`. However `self.build_qubo()` is called there and vice versa. Therefore, I think that these may be reversed.

ref: https://github.com/mdrft/wildcat/blob/master/wildcat/solver/base_solver.py#L15-L18

**Comment by skonb** [comment]
Thanks, this must be.

**Comment by skonb** [comment]
Distributed 0.0.13 on Pypi, would you please check if it works?
Thank you.

**Comment by cia-rana** [comment]
LGTM 👍 
I added some tests and sent a PR #22.
